export const CONFIG = {
    INITIAL_CHARACTERS: 300,
    DAY_DURATION_MS: 1000,
    INITIAL_DATE: new Date(2023, 0, 1),
    MARRIAGE_PROBABILITY: 0.1,
    SEXUAL_BEHAVIOR_PROBABILITY: 0.1 // 每天每对夫妇发生性行为的概率为10%
}